baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ethan Lu'

[menu]
  [[menu.main]]
    name = "about"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "blog"
    url = "/blog"
    weight = 2

  [[menu.main]]
    name = "coursework"
    url = "/coursework"
    weight = 3

  [[menu.main]]
    name = "projects"
    url = "/projects"
    weight = 4

[caches]
  [caches.images]
    dir = ":cacheDir/images"
